name: CI / CD
on: [push,pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd front; npm install; cd ..
      - run: cd front; npm run build; cd ..
      - run: npm install
      - run: npx playwright install --with-deps
      - run: npm test
  
  snyk_scan:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Check current directory 
        run: pwd

      - name: Change directory to project root
        run: cd $GITHUB_WORKSPACE

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk security scan
        run: snyk test
  
  upload_coverage:
    runs-on: ubuntu-latest
    needs: [snyk_scan]
    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: [upload_coverage]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - run: cd front; npm install; cd ..
      - run: cd front; npm run build; cd ..

      - name: 'Deploy'
        run: gcloud app deploy

